# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQe4banfs9Wk2ymbO2wAAgdKkEgd-4Ng
"""

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

SHEET_ID = "1GTcG_AdKIrmY9r1qkyomVcjUgpSSOHkkv-Zuj1lUwNM"
GID = "0"
url_tsv = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=tsv&gid={GID}"

df = pd.read_csv(url_tsv, sep="\t", decimal=",")
print("Colunas lidas:", list(df.columns))
display(df.head())


FEATURE_SETS = {
    "BC":  ["Altura", "Peso"],              # colunas B,C
    "BD":  ["Altura", "Idade"],             # colunas B,D
    "CD":  ["Peso", "Idade"],            # colunas C,D
    "BCD": ["Altura", "Peso", "Idade"] # colunas B,C,D
}

FEATURES = FEATURE_SETS["BCD"]   # <-- troque aqui: "BC", "BD", "CD", "BCD"
TARGET = "Classe"            # coluna F (classe)
for col in FEATURES + ["Classe"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df[TARGET] = df[TARGET].astype(str).str.strip().str.lower()
df = df.dropna(subset=FEATURES + [TARGET]).copy()
print("\nDistribuição do target:")
print(df[TARGET].value_counts())
le = LabelEncoder()
y_all = le.fit_transform(df[TARGET])
X_all = df[FEATURES].values
print("\nClasses:", list(le.classes_))
print("Total linhas válidas:", len(df))
print("Total de colunas:", len(df.columns))

RANDOM_STATE = 42
df_shuffled = df.sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)
test_df  = df_shuffled.iloc[:10].copy()
train_df = df_shuffled.iloc[10:30].copy()
X_train = train_df[FEATURES].values
y_train = le.transform(train_df[TARGET])
X_test  = test_df[FEATURES].values
y_test  = le.transform(test_df[TARGET])
print("\nTreino:", len(train_df), "| Teste:", len(test_df))
print("Atletas:", test_df)

K = 10
WEIGHTS = "distance"  # "uniform" ou "distance"
model = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=K, weights=WEIGHTS))
])
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("\nFeatures usadas:", FEATURES)
print("Acurácia:", accuracy_score(y_test, y_pred))
print("\nRelatório:")
print(classification_report(y_test, y_pred, target_names=le.classes_))
print("Matriz de confusão (real x previsto):")
print(confusion_matrix(y_test, y_pred))